version: '3.8'

services:
  # broker mosquitto
  broker:
    image: eclipse-mosquitto:latest
    container_name: bg_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: always

  # node-red
  nodered:
    image: nodered/node-red:latest
    container_name: bg_nodered
    ports:
      - "1880:1880"
    volumes:
      - ./nodered_data:/data
    env_file:
      - .env  # para poner las variables de entorno en node-red
    depends_on:
      - broker
    restart: always

  # mysql
  database:
    image: mysql:8.0
    container_name: bg_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  # python, opencv y mediapipe
  ia_engine:
    build: ./ia_engine
    container_name: bg_ia_motor
    privileged: true                  # <--- dar acceso de hardware real
    group_add:
      - video                         # <--- comparte el grupo de la webcam
    ports:
      - "8081:8081"  # <--- abre el puerto del video
    volumes:
      - ./ia_engine:/app
      - ./Media:/app/Media   # <--- monta el video de prueba
    devices:
      - "/dev/video0:/dev/video0"
    depends_on:
      - broker
    restart: always

volumes:
  mosquitto_data:
  mosquitto_log:
  mysql_data:
